name: graduation-design
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - ipykernel
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - requests
  - tqdm
  - seaborn
  - patsy
  - pip
  - pip:
      - gensim==4.4.0
      - jieba==0.42.1
      - fasttext-wheel==0.9.2
      - nltk==3.9.3
      - statsmodels==0.14.6
      - umap-learn==0.5.12
      - kneed==0.8.6
